#!/usr/bin/env python3
"""Generate the npm entry points from svg/.

Export names are the icon codes themselves, so what you read in the preview page
is what you import:  happy_rabbit, online_owl, badge_typing, cart_add.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SVG_DIR = ROOT / "svg"
DIST = ROOT / "dist"


def collect(manifest):
    """(code, svg) for every icon, grouped by layer."""
    groups = {"ui": [], "characters": [], "paws": [], "frames": [], "extras": [], "actions": [], "bodies": [], "jobs": [], "badges": [], "status": []}
    for name in manifest["ui"]:
        groups["ui"].append((name, (SVG_DIR / "ui" / f"{name}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for expr in manifest["expressions"] + list(manifest["ratings"]):
            code = f"{expr}_{animal}"
            groups["characters"].append((code, (SVG_DIR / "characters" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for g in manifest["gestures"]:
            code = f"{g}_{animal}"
            groups["paws"].append((code, (SVG_DIR / "paws" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for f in manifest["frames"]:
            code = f"{f}_{animal}"
            groups["frames"].append((code, (SVG_DIR / "frames" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for k in manifest["extras"]:
            code = f"{k}_{animal}"
            groups["extras"].append((code, (SVG_DIR / "extras" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for k in manifest["actions"]:
            code = f"{k}_{animal}"
            groups["actions"].append((code, (SVG_DIR / "actions" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for k in manifest["bodies"]:
            code = f"{k}_{animal}"
            groups["bodies"].append((code, (SVG_DIR / "bodies" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for k in manifest["jobs"]:
            code = f"{k}_{animal}"
            groups["jobs"].append((code, (SVG_DIR / "jobs" / f"{code}.svg").read_text().strip()))
    for status in manifest["badges"]:
        code = f"badge_{status}"
        groups["badges"].append((code, (SVG_DIR / "badges" / f"{code}.svg").read_text().strip()))
    for animal in manifest["animals"]:
        for status in manifest["badges"]:
            code = f"{status}_{animal}"
            groups["status"].append((code, (SVG_DIR / "status" / f"{code}.svg").read_text().strip()))
    return groups


# Reserved and future-reserved words: an icon named after one cannot be a named export.
RESERVED = set("""await break case catch class const continue debugger default delete do else
enum export extends false finally for function if implements import in instanceof interface let
new null package private protected public return static super switch this throw true try typeof
var void while with yield""".split())


def check_codes(codes):
    clashes = sorted(c for c in codes if c in RESERVED)
    if clashes:
        raise SystemExit(f"icon codes clash with JavaScript keywords: {', '.join(clashes)}")
    dupes = sorted({c for c in codes if codes.count(c) > 1})
    if dupes:
        raise SystemExit(f"duplicate icon codes: {', '.join(dupes)}")


def union(values):
    return " | ".join(f'"{v}"' for v in values)


def sprite(entries, name):
    """One <symbol> per icon. Presentation attributes move onto the symbol so
    <use> keeps currentColor and the stroke contract."""
    symbols = []
    for code, svg in entries:
        attrs = dict(re.findall(r'(\w[\w-]*)="([^"]*)"', svg[:svg.index(">")]))
        body = svg[svg.index(">") + 1:svg.rindex("</svg>")]
        body = re.sub(r"<title.*?</title>", "", body, flags=re.S).strip()
        keep = " ".join(f'{k}="{v}"' for k, v in attrs.items()
                        if k in ("fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"))
        symbols.append(f'<symbol id="{code}" viewBox="{attrs["viewBox"]}" {keep}>{body}</symbol>')
    (DIST / f"sprite-{name}.svg").write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n'
        + "\n".join(symbols) + "\n</svg>\n"
    )


REACT = '''// Generated by scripts/build_js.py — do not edit.
import { createElement } from "react";
import { icons } from "./index.mjs";

/**
 * <Icon name="happy_rabbit" size={48} />
 * UI icons inherit the surrounding text colour; characters keep their own palette.
 */
export function Icon({ name, size = 24, style, ...rest }) {
  const raw = icons[name];
  if (!raw) throw new Error(`Unknown icon: ${name}`);
  const html = raw.replace(/\\swidth="\\d+"\\sheight="\\d+"/, ' width="100%" height="100%"');
  return createElement("span", {
    ...rest,
    style: { display: "inline-flex", width: size, height: size, ...style },
    dangerouslySetInnerHTML: { __html: html },
  });
}

export default Icon;
'''


def build():
    manifest = json.loads((ROOT / "icons.json").read_text())
    groups = collect(manifest)
    all_icons = [pair for g in groups.values() for pair in g]
    check_codes([code for code, _ in all_icons])

    DIST.mkdir(exist_ok=True)
    header = "// Generated by scripts/build_js.py — do not edit.\n"
    lookup = ",\n".join(f"  {code}" for code, _ in all_icons)

    meta = (f"export const animals = {json.dumps(list(manifest['animals']))};\n"
            f"export const expressions = {json.dumps(manifest['expressions'])};\n"
            f"export const statuses = {json.dumps(list(manifest['badges']))};\n"
            f"export const uiNames = {json.dumps(manifest['ui'])};\n")

    helpers = """
export const icons = {
%s
};

/** Any icon by its code, e.g. icon("happy_rabbit") or icon("cart_add"). */
export function icon(code) {
  return icons[code];
}

/** A character face: character("rabbit", "sleepy") -> sleepy_rabbit */
export function character(animal, expression = "happy") {
  return icons[`${expression}_${animal}`];
}

/** A character with a status badge: statusIcon("owl", "busy") -> busy_owl */
export function statusIcon(animal, status) {
  return icons[`${status}_${animal}`];
}

/** A standalone status badge: badge("online") -> badge_online */
export function badge(status) {
  return icons[`badge_${status}`];
}

/** Encode markup for a CSS url() or an <img src>. */
export function dataUri(svg) {
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}
""" % lookup

    consts = "\n".join(f"export const {code} = {json.dumps(svg)};" for code, svg in all_icons)
    (DIST / "index.mjs").write_text(header + consts + "\n\n" + meta + helpers)

    cjs_consts = "\n".join(f"const {code} = {json.dumps(svg)};" for code, svg in all_icons)
    (DIST / "index.cjs").write_text(
        header + cjs_consts + "\n\n"
        + meta.replace("export const", "const") + "\n"
        + "const icons = {\n" + lookup + "\n};\n\n"
        + "function icon(code) { return icons[code]; }\n"
        + 'function character(animal, expression = "happy") { return icons[`${expression}_${animal}`]; }\n'
        + "function statusIcon(animal, status) { return icons[`${status}_${animal}`]; }\n"
        + "function badge(status) { return icons[`badge_${status}`]; }\n"
        + "function dataUri(svg) { return `data:image/svg+xml,${encodeURIComponent(svg)}`; }\n\n"
        + "module.exports = { " + ", ".join(code for code, _ in all_icons)
        + ", animals, expressions, statuses, uiNames, icons, icon, character, statusIcon, badge, dataUri };\n"
    )

    decls = "\n".join(f"export declare const {code}: string;" for code, _ in all_icons)
    (DIST / "index.d.ts").write_text(
        header
        + f"export type Animal = {union(manifest['animals'])};\n"
        + f"export type Expression = {union(manifest['expressions'])};\n"
        + f"export type Status = {union(manifest['badges'])};\n"
        + f"export type UiName = {union(manifest['ui'])};\n"
        + "export type CharacterName = `${Expression}_${Animal}`;\n"
        + "export type StatusName = `${Status}_${Animal}`;\n"
        + "export type BadgeName = `badge_${Status}`;\n"
        + "export type IconName = UiName | CharacterName | StatusName | BadgeName;\n\n"
        + "export declare const animals: Animal[];\n"
        + "export declare const expressions: Expression[];\n"
        + "export declare const statuses: Status[];\n"
        + "export declare const uiNames: UiName[];\n"
        + "export declare const icons: Record<IconName, string>;\n\n"
        + "export declare function icon(code: IconName): string;\n"
        + "export declare function character(animal: Animal, expression?: Expression): string;\n"
        + "export declare function statusIcon(animal: Animal, status: Status): string;\n"
        + "export declare function badge(status: Status): string;\n"
        + "export declare function dataUri(svg: string): string;\n\n"
        + decls + "\n"
    )

    (DIST / "react.js").write_text(REACT)
    (DIST / "react.d.ts").write_text(
        header
        + 'import type { CSSProperties, HTMLAttributes } from "react";\n'
        + 'import type { IconName } from "./index";\n\n'
        + "export interface IconProps extends HTMLAttributes<HTMLSpanElement> {\n"
        + "  name: IconName;\n  size?: number | string;\n  style?: CSSProperties;\n}\n\n"
        + "export declare function Icon(props: IconProps): JSX.Element;\n"
        + "export default Icon;\n"
    )

    sprite(groups["ui"], "ui")
    sprite(groups["characters"] + groups["paws"] + groups["frames"] + groups["extras"]
           + groups["actions"] + groups["bodies"] + groups["jobs"]
           + groups["badges"] + groups["status"], "characters")

    total_kb = sum(f.stat().st_size for f in DIST.iterdir()) // 1024
    print(f"wrote dist/ — {len(all_icons)} icons, index + react + 2 sprites ({total_kb} KB)")


if __name__ == "__main__":
    build()
